version: "3.7"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


  flyway:
    image: flyway/flyway:7.15.0
    container_name: flyway_mysql
    command: -url=jdbc:mysql://mysql:3306/miniautorizador  -user=root -password= -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql