spring:
  application:
    name: autorizador

  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      properties:
        hibernate:
          ddl-auto: update
          temp:
            use_jdbc_metadata_defaults: false
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true

    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000